### PR TITLE
Tidy up the repo and make it at least somewhat reproducible

### PR DESCRIPTION
**Pull request by TanyaS08**
Primary change is that I've gone in and made sure all figures match the name that they are assigned in the manuscript. I have also condensed them into two scripts. One for figures in the main manuscripts and the second for figures in the supplementary material.
I've also initiated an `renv` system i.e. there is some sense of dependency management, the caveat is that this comes at a cost since there is at least one case of the code not working so we need to go and fix that if we want to call this project 'reproducible in the current state' (this is issue #27 in case you were wondering).

Okay and now jumping forward to a few checklist items e should probably think about before archiving this repo:

- [x] Fix the issue in #27 
- [x] Probably re-run all the code that is not just the figure code to make sure its all working (I fear that that could be problematic since it might be resting on the shoulders of a much older traitstrap workflow 😰
- [x] Have some sort of re-use licence (always good practice)
- [x] Maybe rename (renumber) some of the scripts since I collapsed a lot to the figure scripts
- [x] Should we have a README for the scripts folder as well? I think it might be useful to designate which files make the computer go brrrr...

### CODE REVIEW

**Comment by bmaitner** [comment]
Re: re-running code: Since we didn't set seed on the simulations, and re-running may lead to minor differences from the current version, I think we should skip that. However, re-running it should be possible as I made sure to include a tar.gz version of the traitstrap version that was used to run the simulations.

Re: license: CC-BY?

Re: renaming/renumbering:  Whatever makes you happy.

Re: readme: if you want?  I think the only particularly slow script is the simulations.

**Comment by TanyaS08** [comment]
why are there merge conflicts on my lovely tidy branch @bmaitner !!?!?!

**Comment by bmaitner** [comment]
> why are there merge conflicts on my lovely tidy branch @bmaitner !!?!?!

image

**Comment by TanyaS08** [comment]
@bmaitner  do you vibe with the changes to the README? [dca422b](https://github.com/EnquistLab/trait_bootstrap_ms/pull/29/commits/dca422bc7c9e6ff8a121f7f95dc981e8cc306ef8)

**Comment by TanyaS08** [comment]
> > why are there merge conflicts on my lovely tidy branch @bmaitner !!?!?!
> 
> image

It exists because _someone_ (I won't mention names _cough_ Maitner _cough_ made changes on master... To a folder which no longer exists...

**Comment by bmaitner** [comment]
> @bmaitner do you vibe with the changes to the README? [dca422b](https://github.com/EnquistLab/trait_bootstrap_ms/pull/29/commits/dca422bc7c9e6ff8a121f7f95dc981e8cc306ef8)

Yes, doubleplusgood!

**Comment by TanyaS08** [comment]
superlatively good

**Comment by TanyaS08** [comment]
I don't have enough admin rights to drop a licence in the settings for this repo - can you jump on that @bmaitner 🥺🥺

**Comment by TanyaS08** [comment]
Last few tasks for you @bmaitner - can you just do the brief summaries of the scripts in the script folder README? I've already templated them for you. Also check if you're happy with the renaming!

**Comment by TanyaS08** [comment]
If you're happy with that we can merge I think

**Comment by TanyaS08** [comment]
🧃🐋

**Pull request merged**
